//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockerUi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MockerUi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version
        ///Boolean
        ///Capital City
        ///Color Name
        ///Color Hex Value
        ///Company Name
        ///Corporate Department
        ///Country
        ///Credit Card Issuer
        ///Credit Card Network
        ///Currency Name
        ///Currency Code
        ///Date
        ///Decimal
        ///Domain Name
        ///File Type
        ///File Extension
        ///Gender
        ///Genre
        ///Integer
        ///Job Title
        ///Language
        ///Language Code
        ///Latitude
        ///Longitude
        ///Military Time
        ///Name
        ///Time
        ///Time Zone
        ///Time Zone Name
        ///Vehicle Manufacturer
        ///Vehicle Model
        ///Week Day.
        /// </summary>
        internal static string DataTypes {
            get {
                return ResourceManager.GetString("DataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MockerData {
            get {
                object obj = ResourceManager.GetObject("MockerData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RandomData {
            get {
                object obj = ResourceManager.GetObject("RandomData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sqlite3 {
            get {
                object obj = ResourceManager.GetObject("sqlite3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORTS
        ///sqlite3_aggregate_context
        ///sqlite3_aggregate_count
        ///sqlite3_auto_extension
        ///sqlite3_backup_finish
        ///sqlite3_backup_init
        ///sqlite3_backup_pagecount
        ///sqlite3_backup_remaining
        ///sqlite3_backup_step
        ///sqlite3_bind_blob
        ///sqlite3_bind_blob64
        ///sqlite3_bind_double
        ///sqlite3_bind_int
        ///sqlite3_bind_int64
        ///sqlite3_bind_null
        ///sqlite3_bind_parameter_count
        ///sqlite3_bind_parameter_index
        ///sqlite3_bind_parameter_name
        ///sqlite3_bind_pointer
        ///sqlite3_bind_text
        ///sqlite3_bind_text16
        ///sqlite3_bind_text64
        ///sqlite3_bind_value
        ///sqlite3_bind_zeroblob
        ///s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sqlite3_definition {
            get {
                return ResourceManager.GetString("sqlite3_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sqlite3_library {
            get {
                object obj = ResourceManager.GetObject("sqlite3_library", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
